// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie_Characters_API.Models;

#nullable disable

namespace Movie_Characters_API.Migrations
{
    [DbContext(typeof(MovieCharactersDbContext))]
    [Migration("20230303135114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieCharacter", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("MovieCharacter");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CharacterId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            CharacterId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            CharacterId = 1
                        },
                        new
                        {
                            MovieId = 2,
                            CharacterId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            CharacterId = 3
                        },
                        new
                        {
                            MovieId = 3,
                            CharacterId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            CharacterId = 5
                        });
                });

            modelBuilder.Entity("Movie_Characters_API.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "The boy who lived",
                            FranchiseId = 1,
                            Gender = "Male",
                            Name = "Harry Potter",
                            Picture = "https://www.imdb.com/title/tt0241527/mediaviewer/rm2113437952"
                        },
                        new
                        {
                            Id = 2,
                            FranchiseId = 1,
                            Gender = "Female",
                            Name = "Hermoine Granger",
                            Picture = "https://www.imdb.com/title/tt0241527/mediaviewer/rm2923487745/"
                        },
                        new
                        {
                            Id = 3,
                            Alias = "Professor Slughorn",
                            FranchiseId = 1,
                            Gender = "Male",
                            Name = "Horace Slughorn",
                            Picture = "https://www.imdb.com/title/tt0417741/mediaviewer/rm1934071552"
                        },
                        new
                        {
                            Id = 4,
                            FranchiseId = 2,
                            Gender = "Male",
                            Name = "Frodo Baggins",
                            Picture = "https://www.imdb.com/title/tt0120737/mediaviewer/rm2645131264"
                        },
                        new
                        {
                            Id = 5,
                            Alias = "Strider",
                            FranchiseId = 2,
                            Gender = "Male",
                            Name = "Aragorn",
                            Picture = "https://www.imdb.com/title/tt0120737/mediaviewer/rm2368970240"
                        });
                });

            modelBuilder.Entity("Movie_Characters_API.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Harry Potter is a film series based on the eponymous novels by J. K. Rowling. The series is produced and distributed by Warner Bros. Pictures and consists of eight fantasy films, beginning with Harry Potter and the Philosopher's Stone (2001) and culminating with Harry Potter and the Deathly Hallows – Part 2 (2011).",
                            Name = "Harry Potter"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Lord of the Rings is a series of three epic fantasy adventure films directed by Peter Jackson, based on the novel The Lord of the Rings by J. R. R. Tolkien. The films are subtitled The Fellowship of the Ring (2001), The Two Towers (2002), and The Return of the King (2003).",
                            Name = "Lord of the Rings"
                        });
                });

            modelBuilder.Entity("Movie_Characters_API.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Trailer")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Chris Colombus",
                            FranchiseId = 1,
                            Genre = "Adventure, Family, Fantasy",
                            MovieTitle = "Harry Potter and the Philosopher's Stone",
                            Picture = "https://www.imdb.com/title/tt0241527/mediaviewer/rm2105413120/",
                            ReleaseYear = 2001,
                            Trailer = "https://www.imdb.com/video/vi3115057433/?playlistId=tt0241527"
                        },
                        new
                        {
                            Id = 2,
                            Director = "David Yates",
                            FranchiseId = 1,
                            Genre = "Action, Adventure, Family, Fantasy, Mystery",
                            MovieTitle = "Harry Potter and the Half-Blood Prince",
                            Picture = "https://www.imdb.com/title/tt0417741/mediaviewer/rm282560512/",
                            ReleaseYear = 2009,
                            Trailer = "https://www.imdb.com/video/vi1061421849/?playlistId=tt0417741"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Peter Jackson",
                            FranchiseId = 2,
                            Genre = "Action, Adventure, Drama, Fantasy",
                            MovieTitle = "The Lord of the Rings: The Fellowship of the Ring",
                            Picture = "https://www.imdb.com/title/tt0120737/mediaviewer/rm3592958976/",
                            ReleaseYear = 2001,
                            Trailer = "https://www.imdb.com/video/vi684573465/?playlistId=tt0120737"
                        });
                });

            modelBuilder.Entity("MovieCharacter", b =>
                {
                    b.HasOne("Movie_Characters_API.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movie_Characters_API.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movie_Characters_API.Models.Movie", b =>
                {
                    b.HasOne("Movie_Characters_API.Models.Franchise", "Franchise")
                        .WithMany("Movies")
                        .HasForeignKey("FranchiseId");

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Movie_Characters_API.Models.Franchise", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
